#!/bin/env bash
#
# Copyright (C) 2018 All Rights Reserved.
#
# Author:          Houmin Wei  <houmin.wei@outlook.com>
# Created:         Fri 12 Jan 2018 06:43:46 PM CST
# Last Modified:   Fri 12 Jan 2018 07:21:32 PM CST

if [[ -f `pwd`/sharedfuncs ]]; then
    source `pwd`/sharedfuncs
else
    echo "missing file: sharedfuncs"
    exit 1
fi

#ARCHLINUX INSTALL SCRIPTS MODE {{{

#SELECT KEYMAP {{{
select_keymap() {

}
#}}}

#DEFAULT EDITOR {{{
select_editor() {

}
#}}}

#MIRRORLIST {{{
configure_mirrorlist() {

}
#}}}

#SETUP ALTERNATIVE DNS {{{
setup_alt_dns() {

}
#}}}

#UMOUNT PARTITIONS {{{
umount_partitions() {

}
#}}}

#SELECT DEVICE {{{
select_device() {

}
#}}}

#CREATE PARTITION SCHEME {{{
create_partition_scheme() {

}
#}}}

#SETUP PARTITION {{{
create_partition() {

}
#}}}

#SETUP LUKS {{{
setup_luks() {

}
#}}}

#SETUP LVM {{{
setup_lvm() {

}
#}}}

#SELECT|FORMAT PARTITIONS {{{
format_partitions() {

}
#}}}

#INSTALL BASE SYSTEM {{{
select_linue_version() {

}

install_base_system() {

}
#}}}

#CONFIGURE KEYMAP {{{
configure_keymap() {

}
#}}}

#CONFIGURE FSTAB {{{
configure_fstab() {

}
#}}}

#CONFIGURE HOSTNAME {{{
configure_hostname() {

}
#}}}

#CONFIGURE TIMEZONE {{{
configure_timezone() {

}
#}}}

#CONFIGURE HARDWARECLOCK {{{
configure_hardwareclock() {

}
#}}}

#CONFIGURE LOCALE {{{
configure_locale() {

}
#}}}

#CONFIGURE MKINITCPIO {{{
configure_mkinitcpio() {

}
#}}}

#INSTALL BOOTLOADER {{{
install_bootloader() {

}
#}}}

#CONFIGURE BOOTLOADER {{{
configure_bootloader() {

}
#}}}

#ROOT PASSWORD {{{
root_password() {

}
#}}}

#FINISH {{{
finish() {

}
#}}}

print_title "https://wiki.archlinux.org/index.php/Arch_Install_Scripts"
print_info "The Arch Install Scripts are a set of BASH scripts that simplify Arch Installation"
pause_function
check_boot_system
check_connection
check_trim
pacman -Sy
while true
do
    print_title "Archlinux Ultimate Install"
    echo " 1) $(mainmenu_item "${checklist[1]}" "Select Keymap"             "${KEYMAP}" )"
    echo " 2) $(mainmenu_item "${checklist[2]}" "Select Editor"             "${EDITOR}" )"
    echo " 3) $(mainmenu_item "${checklist[3]}" "Configure Mirrorlist"      "${contry_name} (${country_code})" )"
    echo " 4) $(mainmenu_item "${checklist[4]}" "Partition Scheme"          "${partition_layout}: ${partition}(${filesystem}) swap(${swap_type})" )"
    echo " 5) $(mainmenu_item "${checklist[5]}" "Install Base System")"
    echo " 6) $(mainmenu_item "${checklist[6]}" "Configure Fstab"           "${fstab}" )"
    echo " 7) $(mainmenu_item "${checklist[7]}" "Configure Hostname"        "${host_name}" )"
    echo " 8) $(mainmenu_item "${checklist[8]}" "Configure Timezone"        "${ZONE}/${SUBZONE}" )"
    echo " 9) $(mainmenu_item "${checklist[9]}" "Configure Hardware Clock"  "${hwclock}" )"
    echo "10) $(mainmenu_item "${checklist[10]}" "Configure Locale"         "${LOCALE}" )"
    echo "11) $(mainmenu_item "${checklist[11]}" "Configure Mkinitcpio")"
    echo "12) $(mainmenu_item "${checklist[12]}" "Install Bootloader"       "${bootloader}" )"
    echo "13) $(mainmenu_item "${checklist[13]}" "Reboot Password")"
    echo ""
    echo " d) Done"
    echo ""
    read_input_options
    for OPT in ${OPTIONS[@]}; do
        case "$OPT" in
            1)
                select_keymap
                checklist[1]=1
                ;;
            2)
                select_editor
                checklist[2]=1
                ;;
            3)
                configure_mirrorlist
                checklist[3]=1
                ;;
            4)
                umount_partitions
                create_partition_scheme
                format_partitions
                checklist[4]=1
                ;;
            5)
                install_base_system
                configure_keymap
                setup_alt_dns
                checklist[5]=1
                ;;
            6)
                configure_fstab
                checklist[6]=1
                ;;
            7)
                configure_hostname
                checklist[7]=1
                ;;
            8)
                configure_timezone
                checklist[8]=1
                ;;
            9)
                configure_hardwareclock
                checklist[9]=1
                ;;
            10)
                configure_locale
                checklist[10]=1
                ;;
            11)
                configure_mkinitcpio
                checklist[11]=1
                ;;
            12)
                install_bootloader
                configure_bootloader
                checklist[12]=1
                ;;
            13)
                root_password
                checklist[13]=1
                ;;
            "d")
                finish
                ;;
            *)
                invalid_option
                ;;
        esac
    done
done
#}}}
